print("Welcome to this little game")
print("Tell me something about you")
name=input("What is your name? ")
print("Hello")
print(name)
color=input("Tell me "+name+ " what is your favorite color ")
print("your favotite color is.......")
print(" ....."+color+" !!!")
print("That color is amazing!! My daughter likes "+color+" too!!")
print("Thanks for playing "+name+" !! have a wonderful day!!")
